baseURL = 'https://daemonlord.in/'
title = 'Daemon Lord'
theme = 'terminal'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
copyright = "© 2025 Daemonlord"

[params]
  contentTypeName = 'posts'
  showMenuItems = 5
  showLanguageSelector = true
  showFooter = true
  fullWidthTheme = true
  centerTheme = true
  showLastUpdated = true

[languages]
  [languages.en]
    languageName = 'English'
    title = "Daemonlord"
    weight = 1
    contentDir = 'content/en'

    [languages.en.params]
      menuMore = 'Show more'
      readMore = 'Read more'

      [languages.en.params.logo]
        logoText = 'Daemon Lord'
        logoHomeLink = '/en/'

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = 'home'
        name = 'Home'
        url = '/en/'
        weight = 1

      [[languages.en.menu.main]]
        identifier = 'support'
        name = 'Buy Me a Coffee'
        url = '#'
        weight = 99

      # [[languages.en.menu.main]]
      #   identifier = 'posts'
      #   name = 'Posts'
      #   url = '/en/posts'
      #   weight = 2

  [languages.ja]
    languageName = '日本語  '
    title = 'デーモンロード'
    weight = 1
    contentDir = 'content/ja'

    [languages.ja.params]
      menuMore = 'もっと見る'
      readMore = '続きを読む'

      [languages.ja.params.logo]
        logoText = 'デーモンロード'
        logoHomeLink = '/ja/'

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = 'home'
        name = 'ホーム'
        url = '/ja/'
        weight = 1

      [[languages.ja.menu.main]]
        identifier = 'support'
        name = 'コーヒーを奢る'
        url = '#'
        weight = 99

      # [[languages.ja.menu.main]]
      #   identifier = 'posts'
      #   name = '投稿'
      #   url = '/ja/posts'
      #   weight = 2
